name: CI/CD Flask App

on:
  push: 
    branches: ["main"]

env:
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/flask-app
  IMAGE_TAG: latest

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
        context: 
        push: true
        tags: |
            ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
deploy:
  needs: build-and-push
  runs-on: ubuntu-latest
  steps: 
      - name: SSH deploy to EC2
      - uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e
            cd ~/Devops-Journey/docker-python-flask
          # ensure DOCKER_USER is set for compose substitution
          grep -q '^DOCKER_USER=' .env || echo "DOCKER_USER=${{ secrets.DOCKER_USERNAME }}" >> .env
          docker compose -f docker-compose.prod.yml pull
          docker compose -f docker-compose.prod.yml up -d
          docker image prune -f
          docker compose -f docker-compose.prod.yml ps


