version: "3.9"

services:
  web:
    build: ./web
    ports:
      - "8080:80"
    depends_on:
      - api
    networks:
      - app-net

  api:
    build: ./api
    ports:
      - "5000:5000"
    depends_on:
      - redis
    networks:
      - app-net

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-net

networks:
  app-net:
    driver: bridge

