pipeline {
   agent any
   environment {APP = 'jenkins-express'}
   stages {
      stage('Checkout')  { steps { checkout scm } }
      stage('Install & Test') { steps { sh 'npm ci && npm test' } }
      stage('Build Image') {
         steps {
            sh '''
                 docker build -t ${APP}:${BUILD_NUMBER} .
                 docker tag ${APP}:${BUILD_NUMBER} ${APP}:latest
               '''
         }
      }
      stage('Run Container') {
         steps {
            sh '''
                 docker ps -q --filter name=${APP} | xargs -r docker rm -f 
                 docker run -d --name ${APP} -p 3000:3000 ${APP}:latest
               '''
         }
      }
   }
   post {
      always {sh 'docker image prune -f || true'}
      success {echo 'Up at http://3.150.94.17:3000'}
   }
}