version: "3.9"

services:
  web:
    build: .
    container_name: flask-web
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql://appuser:apppass@db:5432/appdb}
      FLASK_ENV: development
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppass
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U appuser -d appdb"]
      interval: 5s        # <-- was 'internal'
      timeout: 5s
      retries: 10
      start_period: 5s    # optional, but useful on small instances

volumes:
  pgdata:
