project_id     = "devops-reliability-lab"
region         = "us-central1"
zone           = "us-central1-a"
vpc_name       = "devops-vpc-prod"
subnet_name    = "devops-subnet-prod"
firewall_name  = "devops-firewall-prod"
vm_name        = "devops-vm"
env            = "prod"
