services:
  web:
    image: ghcr.io/$gerardinhoo/gh-actions-node-docker:${TAG:-latest}
    container_name: ga-demo
    restart: unless-stopped
    ports:
      - '80:3000'
    environment:
      - NODE_ENV=production
