services:
  web:
    image: ghcr.io/${GH_USER}/gh-actions-node-docker:${TAG:-latest} # value will be overridden
    container_name: ga-demo
    restart: unless-stopped
    ports:
      - '80:3000'
    environment:
      - NODE_ENV=production
