name: GitHub Actions CI/CD

on:
  push:
    branches: ['main']
    paths:
      - 'gh-actions-node-docker/**'
      - '.github/workflows/ci-cd-gh-actions-node-docker.yml'
  workflow_dispatch:

permissions:
  contents: read

env:
  IMAGE_NAME: gh-actions-node-docker

jobs:
  ci-build-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: gh-actions-node-docker
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install
        run: npm install

      - name: Test
        run: npm test

      - name: Build container image
        uses: docker/build-push-action@v6
        with:
          context: ./gh-actions-node-docker
          push: false
          tags: ${{ env.IMAGE_NAME }}:ci
