name: CI (legacy projects)

on:
  push:
    branches: ['main']
    paths:
      - 'simple-node-api/**'
      - 'docker-python-flask/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t gerardinhoo/simple-node-api ./simple-node-api

      - name: Push Docker image
        run: docker push gerardinhoo/simple-node-api
