name: CI (legacy projects)

on:
  push:
    branches: ['main']
    paths:
      - 'simple-node-api/**'
      - 'docker-python-flask/**'
  workflow_dispatch:

jobs:
  build-simple-node-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: ./simple-node-api
          push: true
          tags: gerardinhoo/simple-node-api:latest

  build-docker-python-flask:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: ./docker-python-flask
          push: true
          tags: gerardinhoo/docker-python-flask:latest
